import Architect
import FLT.Data.Hurwitz
import FLT.Data.QHat

open scoped TensorProduct

/-- The base change of the Hurwitz quaternions to ZHat. -/
noncomputable def HurwitzHat : Type := 𝓞 ⊗[ℤ] ZHat

namespace HurwitzHat

/-- The base change of the Hurwitz quaternions to ZHat. -/
scoped notation "𝓞^" => HurwitzHat

noncomputable instance : Ring 𝓞^ := Algebra.TensorProduct.instRing

end HurwitzHat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
noncomputable def HurwitzRat : Type := ℚ ⊗[ℤ] 𝓞

namespace HurwitzRat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
scoped notation "D" => HurwitzRat

noncomputable instance : Ring D := Algebra.TensorProduct.instRing

end HurwitzRat

open scoped HurwitzRat HurwitzHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
noncomputable def HurwitzRatHat : Type := D ⊗[ℤ] ZHat

namespace HurwitzRatHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
scoped notation "D^" => HurwitzRatHat

noncomputable instance : Ring D^ := Algebra.TensorProduct.instRing

/-- The inclusion from D=ℚ+ℚi+ℚj+ℚk to D ⊗ 𝔸, with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₁ : D →ₐ[ℤ] D^ := Algebra.TensorProduct.includeLeft
-- (Algebra.TensorProduct.assoc ℤ ℚ 𝓞 ZHat).symm.trans Algebra.TensorProduct.includeLeft

lemma injective_hRat :
    Function.Injective j₁ := sorry -- flatness

/-- The inclusion from the profinite Hurwitz quaternions to to 𝔸+𝔸i+𝔸j+𝔸k,
with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₂ : 𝓞^ →ₐ[ℤ] D^ :=
  ((Algebra.TensorProduct.assoc ℤ ℤ ℚ 𝓞 ZHat).symm : ℚ ⊗ 𝓞^ ≃ₐ[ℤ] D ⊗ ZHat).toAlgHom.comp
  (Algebra.TensorProduct.includeRight : 𝓞^ →ₐ[ℤ] ℚ ⊗ 𝓞^)

lemma injective_zHat :
    Function.Injective j₂ := sorry -- flatness

-- should I rearrange tensors? Not sure if D^ should be (ℚ ⊗ 𝓞) ⊗ ℤhat or ℚ ⊗ (𝓞 ⊗ Zhat)
@[blueprint
  "HurwitzRatHat.canonicalForm"
  (statement := /-- Every element of $\widehat{D}$ can be written as $z/N$ with $z\in\calOhat$ and
    $N\in\N^+$. -/)
  (proof := /-- Same as the proof for $\Qhat$. -/)
  (latexEnv := "lemma")]
lemma canonicalForm (z : D^) : ∃ (N : ℕ+) (z' : 𝓞^), z = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z' := by
  sorry

@[blueprint
  "HurwitzRatHat.completed_units"
  (statement := /-- The group of units of $\widehat{D}$ is $D^\times\calOhat^\times$.
    More precisely, every element of $\widehat{D}^\times$ can be written as a product $\delta u$
    with $\delta\in D^\times$ and $u\in\calOhat^\times$. -/)
  (proof := /-- Given an element $x$ of $\widehat{D}^\times$, we can use
    lemma~\ref{HurwitzRatHat.canonicalForm}
    to write it as $z/N$ with $N$ a positive integer
    and $z\in\widehat{\calO}$. Note that $N$ is central and in $D^\times$. Similarly, we can
    write $x^{-1}$ as $y/M$ with $M$ a positive integer and $y\in\widehat{\calO}$. Then
    $1=xx^{-1}=zy/NM$ and so $zy=NM=MN$, and $1=x^{-1}x=yz/MN$ so $yz=MN$ too. In particular $y$
    both left and right divides a positive integer.
    
    Now consider the left ideal $\widehat{\calO}y$ generated by $y$. We've just seen that
    this ideal has nontrivial intersection with $\calO$, because it contains $MN>0$. Hence
    its intersection with $\calO$ is a nonzero left ideal of $\calO$, which is
    hence principal by corollary~\ref{Hurwitz.left_ideal_princ}. Write it as $\calO\alpha$
    with $0\not=\alpha\in\calO$.
    
    It suffices to show that $\calOhat\alpha=\calOhat y$. For this would imply that
    $u\alpha=y$ and $vy=\alpha$ for some $u,v\in\calOhat$ and thus $(vu-1)\alpha=0$
    and $(uv-1)y=0$, and both $\alpha$ and $y$ are left divisors of positive integers
    (the norm of $\alpha$, and $MN$ respectively), so now using the fact that $\calOhat$
    is $\Z$-torsion-free (is the tensor product of torsion-free abelian groups torsion-free? That
    would be a cheap way of doing it. Otherwise use $\calO=\Z^4$) we deduce that $u$ and $v$
    are units, and thus $x^{-1}=\frac{1}{M}u\alpha$ so $x=(M\alpha^{-1})v\in
    D^\times\calOhat^\times$.
    
    What remains is this. We have $y\in\calOhat$ which left and right divides some positive integer.
    We've defined $0\not=\alpha\in\calO$ such that $\calO\alpha$ is the pullback of the
    abelian group $\calOhat y$ along the map $\calO\to\calOhat$. We need to show that when we push
    this ideal $\calO\alpha$ forwards to $\calOhat$ we get $\calOhat y$ again. The fact that
    $\calOhat\alpha\subseteq\calOhat y$ is easy, because $\alpha\in\calOhat y$ by definition.
    So it remains to show that $y\in\calOhat\alpha$.
    
    Let's define $T$ to be a positive integer which is both a left and right multiple of
    both $y$ and $\alpha$ (for example $T=MN\alpha\overline{\alpha}$ will do). Now note that we
    have an isomorphism $\calO/T\calO=\calOhat/T\calOhat$, so we can choose
    some $\beta\in\calO$ such that $\beta-y\in T\calOhat$ is a multiple of $T$. Next note that
    $\beta\in y+\calOhat T\subset \calOhat y$ is in $\calOhat y\cap\calO=\calO\alpha$, meaning
    $\beta=\gamma\alpha$ for some $\gamma\in\calO$.
    Hence $y\in\beta+\calOhat T\subseteq\calOhat\alpha$. -/)]
lemma completed_units (z : D^ˣ) : ∃ (u : Dˣ) (v : 𝓞^ˣ), (z : D^) = j₁ u * j₂ v := sorry

end HurwitzRatHat
